### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by kgoldthorpe** [HalfdanJ/svelte-adapter-appengine#78]
Upon adding the svelte-adapter-appengine I get the following error on build using strict typescript with lang="ts" in script tags.

```
<script lang="ts">
 2 |    import AuthHeader from '$lib/AuthHeader.svelte'
 3 |    import type { PageData } from './$types'
                    ^
 4 |
 5 |    export let data: PageData
error during build:
ParseError: Unexpected token
    at error (file:///C:/gocode/src/Setyr/Web/node_modules/svelte/compiler.mjs:16669:19)
    at Parser$1.error (file:///C:/gocode/src/Setyr/Web/node_modules/svelte/compiler.mjs:16747:9)
    at Parser$1.acorn_error (file:///C:/gocode/src/Setyr/Web/node_modules/svelte/compiler.mjs:16741:14)
    at Object.read_script [as read] (file:///C:/gocode/src/Setyr/Web/node_modules/svelte/compiler.mjs:8793:16)
    at tag (file:///C:/gocode/src/Setyr/Web/node_modules/svelte/compiler.mjs:15695:33)
    at new Parser$1 (file:///C:/gocode/src/Setyr/Web/node_modules/svelte/compiler.mjs:16706:21)
    at parse$I (file:///C:/gocode/src/Setyr/Web/node_modules/svelte/compiler.mjs:16838:20)
    at compile (file:///C:/gocode/src/Setyr/Web/node_modules/svelte/compiler.mjs:46610:17)
    at compileSvelte2 (file:///C:/gocode/src/Setyr/Web/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:466:22)
    at async Object.transform (file:///C:/gocode/src/Setyr/Web/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:2202:25)

svelte.config
import adapter from '@sveltejs/adapter-auto'
import { sveltekit, vitePreprocess } from '@sveltejs/kit/vite'

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://kit.svelte.dev/docs/integrations#preprocessors
	// for more information about preprocessors
	preprocess: vitePreprocess(),

	kit: {
		adapter: adapter()
	}
}

export default config

// import appengine from 'svelte-adapter-appengine'

// /** @type {import('@sveltejs/kit').Config} */
// export default {
// 	kit: {
// 		adapter: appengine()
// 	}
// }
```
With the default config everything works as expected.
Commenting out the "export default config" and uncommenting the adapter produces the error
FYI adding the "target" per the docs throws an exception

**Comment by HalfdanJ** [comment]
Have you tried leaving the `preprocess: vitePreprocess()` line in?

**Comment by HalfdanJ** [comment]
I've update the readme to the latest svelte.config.js format now.

**Comment by kgoldthorpe** [comment]
Yes.  I don't change that line.  Here are the things I've tried.

- All packages are up to date
- Node is version 18.13.0, NPM is version 9.4.1
- Set the ES target to the previous version including es2021
- reboot vs code and my computer

I should also mention that I successfully deployed to GCP with the svelte adapter before implementing PageData, PageServerLoad, fetch, etc...

**Comment by kgoldthorpe** [comment]
I've updated my svelte.config to the updated readme and the issue is resolved.  I appreciate your help.

**Comment by kgoldthorpe** [comment]
The issue has been resolved
